### PR TITLE
Filter capabilities

### PR DESCRIPTION
**Pull request by pereirinha**
Hey Steve:

I have a use case where we need more control on who can access this page.
Adding this filter is a good way to help extend this.

### CODE REVIEW

**Comment by stevegrunwell** [comment]
@pereirinha Totally on-board with adding the filter, and thank you for your contribution! Before I merge it + tag a new release, could you please add inline documentation for the filter + information about it to the README.md file?

**Comment by pereirinha** [comment]
@stevegrunwell Is there anything else I can do to help you on this?

**Comment by stevegrunwell** [comment]
@pereirinha nope, I've just been busy and failed to merge + tag a new release. I'll take care of that over lunch today.

**Comment by stevegrunwell** [comment]
Following up, version 0.5.0 has been released. Thanks again for your contribution!

**Comment by pereirinha** [comment]
You welcome @stevegrunwell. Thank you for merging the PR ;)

**Pull request merged**
